c_compiler:
  - gcc                        # [linux]
cxx_compiler:
  - gxx                        # [linux]
cgo_compiler:
  - go-cgo
cuda_compiler:
  - nvcc
cuda_compiler_version:
  - None
  - 10.2                       # [linux64]
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
