c_compiler:
  - gcc                        # [linux]
c_compiler_version:            # [unix]
  - 8                          # [linux64]
cxx_compiler:
  - gxx                        # [linux]
cxx_compiler_version:          # [unix]
  - 8                          # [linux64]
cgo_compiler:
  - go-cgo
cuda_compiler:
  - nvcc
boost_cpp:
  - 1.72
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
