

{% set version = "5.10.1" %}
{% set buildnum = "0" %}
{% set install_base = "opt/omnisci" %}

package:
  name: intel_repack
  version: {{ version }}

source:
  - url: https://anaconda.org/conda-forge/omniscidb-common/{{ version }}/download/{{ target_platform }}/omniscidb-common-{{ version }}-h1234567_{{ buildnum }}.tar.bz2
    folder: omniscidb-common
  - url: https://anaconda.org/conda-forge/omniscidbe/{{ version }}/download/{{ target_platform }}/omniscidbe-{{ version }}-h1234567_{{ buildnum }}_cpu.tar.bz2
    folder: omniscidbe
  - url: https://anaconda.org/conda-forge/pyomniscidbe/{{ version }}/download/{{ target_platform }}/pyomniscidbe-{{ version }}-{{ 'py' ~ python | replace('.', '') }}h1234567_{{ buildnum }}_cpu.tar.bz2
    folder: pyomniscidbe

build:
  number: {{ buildnum|int }}
  binary_relocation: false
  detect_binary_files_with_prefix: false
  skip: True  # [not (x86 and linux)]
  runpath_whitelist:
    - $ORIGIN

outputs:
  - name: omniscidb-common
    version: {{ version }}
    script: repack.sh   # [unix]
    build:
      skip: True  # [not (x86 and linux)]
      run_exports:
        - {{ pin_subpackage('omniscidb-common',  max_pin='x.x.x') }}
    requirements:
      build:
        # c compiler is specified here to get run constraint pins correct, presumably...
        - {{ compiler('c') }}
    test:
      commands:
        # Test installation
        # doc
        - test -f ${PREFIX}/share/doc/omnisci/LICENSE.md
        # data
        - test -d ${PREFIX}/{{ install_base }}/ThirdParty/gdal-data
        # thrift
        - test -f ${PREFIX}/{{ install_base }}/completion_hints.thrift
        - test -f ${PREFIX}/{{ install_base }}/omnisci.thrift
        - test -f ${PREFIX}/{{ install_base }}/common.thrift
        - test -f ${PREFIX}/{{ install_base }}/QueryEngine/serialized_result_set.thrift
        - test -f ${PREFIX}/{{ install_base }}/QueryEngine/extension_functions.thrift
        # includes
        - test -f ${PREFIX}/include/omnisci/Shared/funcannotations.h
        - test -f ${PREFIX}/include/omnisci/Shared/InlineNullValues.h
        - test -f ${PREFIX}/include/omnisci/Logger/Logger.h
        # QE
        - test -f ${PREFIX}/include/omnisci/QueryEngine/OmniSciTypes.h
        - test -f ${PREFIX}/{{ install_base }}/QueryEngine/RuntimeFunctions.bc
        - test -f ${PREFIX}/{{ install_base }}/QueryEngine/RuntimeFunctions.bc
        - test -f ${PREFIX}/{{ install_base }}/QueryEngine/ExtensionFunctions.ast
        # jar
        - test -f ${PREFIX}/{{ install_base }}/bin/omnisci-utility-{{ version }}.jar
        - test -f ${PREFIX}/{{ install_base }}/bin/omnisci-jdbc-{{ version }}.jar
        - test -f ${PREFIX}/{{ install_base }}/bin/calcite-1.0-SNAPSHOT-jar-with-dependencies.jar
        # Unspecified
        - test -f ${PREFIX}/{{ install_base }}/bin/startomnisci
        - test -f ${PREFIX}/{{ install_base }}/bin/omnisci_insert_sample_data
        #
        - test -f ${PREFIX}/{{ install_base }}/bin/generate_cert
    about:
      home: https://www.omnisci.com/
      license: Apache-2.0
      license_family: APACHE
      license_file: omniscidb-common/share/doc/omnisci/LICENSE.md
      summary: The OmniSci database common files.
      description: |
        OmniSciDB is an in-memory, column store, SQL relational database
        that was designed from the ground up to run on GPUs.
        This package is a repackaged set of binaries obtained directly from Intel\'s anaconda.org conda-forge channel.
      doc_url: https://www.omnisci.com/docs/latest/
      dev_url: https://github.com/omnisci/omniscidb

  # - name: pyomniscidbe
  #   script: repack.sh   # [unix]
  #   script: repack.bat  # [win]
  #   build:
  #     run_exports:
  #       - {{ pin_subpackage('pyomniscidbe',  max_pin='x.x.x') }}
  #   requirements:
  #     build:
  #       # c compiler is specified here to get run constraint pins correct, presumably..
  #       - {{ compiler('c') }}
  #     host:
  #       - {{ pin_subpackage('omniscidbe', exact=True) }}
  #     run:
  #       - python
  #       - {{ pin_subpackage('omniscidbe', exact=True) }}

  #   test:
  #     requires:
  #       - pytest
  #       - numpy
  #       - pandas
  #     imports:
  #       - omniscidbe
  #     source_files:
  #       - Embedded/test/
  #       - Tests/
  #     commands:
  #       - python Embedded/test/test_fsi.py
  #       - python Embedded/test/test_readcsv.py
  #       - pytest -sv Embedded/test/test_exceptions.py
  #   about:
  #     home: https://www.omnisci.com/
  #     license: Apache-2.0
  #     license_family: APACHE
  #     license_file: LICENSE.md
  #     summary: The OmniSci database

  #     description: |
  #       OmniSciDB is an in-memory, column store, SQL relational database
  #       that was designed from the ground up to run on GPUs.
  #     doc_url: https://www.omnisci.com/docs/latest/
  #     dev_url: https://github.com/omnisci/omniscidb